language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
script: "RAILS_ENV=test bundle exec rails test"
env:
  - DB=sqlite
services:
  - xvfb
before_script:
  - "RAILS_ENV=test bundle exec rake db:schema:load"
notifications:
  email:
    - kdbeswic@ncsu.edu
