language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
script: "RAILS_ENV=test bundle exec rails test"
env:
  - DB=sqlite  
addons:
  apt:
    packages:
      - libqtwebkit-dev
services:
  - xvfb
before_script:
  - "RAILS_ENV=test bundle exec rake db:schema:load"
notifications:
  email:
    - kdbeswic@ncsu.edu
